name: Build and tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Yarn install
        run: yarn install

      - name: Yarn build
        run: yarn build

      - name: Jest tests
        run: yarn test

      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh

      - name: Run REAMDE test
        run: /home/runner/.deno/bin/deno run -A --unstable ./readme-test.deno.ts
